name = "ConstrainedDFO"
uuid = "12b7d493-2132-44b7-a248-b28c3eff80ff"
authors = ["Sacha Benarroch-Lelong"]
version = "1.0.0-DEV"

[deps]
NOMAD = "02130f1c-4665-5b79-af82-ff1385104aa0"

[compat]
NOMAD = "2.4.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
