name = "ConstrainedDFO"
uuid = "12b7d493-2132-44b7-a248-b28c3eff80ff"
version = "1.0.0-DEV"
authors = ["Sacha Benarroch-Lelong"]

[deps]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NOMAD = "02130f1c-4665-5b79-af82-ff1385104aa0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
CUTEst = "1.3.6"
Debugger = "0.7.15"
ForwardDiff = "1.3.0"
Ipopt = "1.11.0"
JuMP = "1.29.3"
LinearAlgebra = "1.12.0"
Manifolds = "0.11.2"
ManifoldsBase = "2.2.0"
Manopt = "0.5.29"
NLPModels = "0.21.6"
NOMAD = "2.4.2"
Plots = "1.41.2"
Printf = "1.11.0"
Random = "1.11.0"
Revise = "3.12.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
